spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.SQL=DEBUG

# Auth
spring.security.oauth2.client.registration.google.client-id=623831654772-8qe130cclprgm853u5i3l7rpinjksc5j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=Ov23liGcGvjtwr05RE66
spring.security.oauth2.client.registration.github.client-secret=c0e0e5a96ac31b88eb08b1f6643ebfda38a75122
spring.security.oauth2.client.registration.github.scope=user:email

app.jwt.secret=928482347823743829923842834729378829329492424222
app.jwt.expiration-ms=86400000
